name: <+pipeline.variables.serviceName>
replicas: 1

virtualPath: <+pipeline.variables.virtualPath>

image: <+artifact.image>
imagePolicy: Always
dockercfg: <+artifact.imagePullSecret>

createNamespace: true
namespace: <+infra.namespace>

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName
serviceType: ClusterIP

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.
servicePort: 80
serviceTargetPort: 80

# Specify all environment variables to be added to the container.
# The following two maps, config and secrets, are put into a ConfigMap
# and a Secret, respectively.
# Both are added to the container environment in podSpec as envFrom source.
env:
  config:
    STABLE_ENDPOINT: ${serviceVariable.stableEndpoint}
    CANARY_ENDPOINT: ${serviceVariable.canaryEndpoint}
    LOG_CONFIG_LABELS: |-
      {
        logsPerMinute: "Logs per minute",
        errorRate: "Error rate (%)",
        errorMessage: "Error message"
      }
    METRIC_CONFIG_LABELS: |-
      {
        callsPerMinute: "Calls per minute",
        errorRate: "Error rate (%)",
        minErrorValue: "Error value min",
        maxErrorValue: "Error value max",
        shouldDoDelayedCalls: "Delayed calls enabled"
      }
